---
apiVersion: "kyverno.io/v2beta1"
kind: "PolicyException"
metadata:
  labels:
    cleanup.kyverno.io/ttl: "2026-03-06T083137Z"
  name: "per-demo-remediator-pr515-83pqzxj6-0"
  namespace: "kyverno"
spec:
  exceptions:
  - policyName: "disallow-privileged-containers"
    ruleNames:
    - "autogen-privileged-containers"
    - "autogen-autogen-privileged-containers"
  match:
    any:
    - resources:
        kinds:
        - "Deployment"
        names:
        - "nginx"
        namespaces: []
