apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-test
  namespace: resopz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-test
  template:
    metadata:
      labels:
        app: memory-test
    spec:
      containers:
        - name: web
          image: nginx:1.27
          resources:
            requests:
              cpu: "100m"
              memory: "137Mi"   # Reduced to comply with Kyverno rule
            limits:
              cpu: "200m"
              memory: "500Mi"
