apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/demo-remediator.git
    targetRevision: helm_chart
    path: nginx-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://E5D5394B9E5D3CE9309760975DC52F98.yl4.us-west-1.eks.amazonaws.com
    namespace: nginx-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
