apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resopz-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/demo-remediator.git
    targetRevision: resource-optimization
    path: apps/resopz
  destination:
    server: https://kubernetes.default.svc
    namespace: resopz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

