# Default values for nginx-chart.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Security context settings
securityContext:
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN

# Container port configuration
containerPort: 80
hostPort: 80

# Volume configuration
volumes:
  hostPath:
    enabled: true
    path: /etc
    name: host-vol

# Pod annotations
podAnnotations:
  container.apparmor.security.beta.kubernetes.io/nginx: unconfined

# Resource limits and requests
resources: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Labels
labels:
  app: nginx
