affinity: {}
containerPort: 81
fullnameOverride: ""
hostPort: 81
image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: latest
labels:
    app: nginx
metadata:
    name: nginx-helm-demo
    namespace: nginx-helm
nameOverride: ""
nodeSelector: {}
podAnnotations:
    container.apparmor.security.beta.kubernetes.io/nginx-chart: unconfined
replicaCount: 1
resources: {}
securityContext:
    capabilities:
        add:
            - SYS_ADMIN
    privileged: true
service:
    port: 81
    targetPort: 81
    type: ClusterIP
tolerations: []
volumes:
    hostPath:
        enabled: true
        name:
            - emptyDir: {}
              name: host-vol
        path: /etc
