apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        container.apparmor.security.beta.kubernetes.io/nginx: unconfined
    labels:
        app: nginx
        app.kubernetes.io/name: nginx
    name: nginx
    namespace: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
                app.kubernetes.io/name: nginx
        spec:
            securityContext:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            containers:
                - image: nginx:1.25
                  name: nginx
                  livenessProbe:
                    httpGet:
                        path: /
                        port: 80
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  ports:
                    - containerPort: 80
                  resources:
                    limits:
                        cpu: 300m
                        memory: 256Mi
                    requests:
                        cpu: 150m
                        memory: 128Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            - ALL
                            - CAP_NET_RAW
                    privileged: false
                    readOnlyRootFilesystem: true
                    runAsNonRoot: true
                    seccompProfile:
                        type: RuntimeDefault
            volumes:
                - emptyDir: {}
                  name: host-vol
