apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.volumes.hostPath.enabled }}
      volumes:
      - name: {{ .Values.volumes.hostPath.name }}
        emptyDir: {}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        securityContext:
          privileged: false
          {{- if .Values.securityContext.capabilities }}
          capabilities:
            {{- toYaml .Values.securityContext.capabilities | nindent 12 }}
          {{- end }}
        {{- if .Values.volumes.hostPath.enabled }}
        volumeMounts:
        - name: {{ .Values.volumes.hostPath.name }}
          mountPath: /mnt/host-vol
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
